In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn import linear_model
import statsmodels.formula.api as smf

In [2]:
df=pd.read_excel('Table_8_Offenses_Known_to_Law_Enforcement_by_New_York_by_City_2014.xls',skiprows=[0,1,2,3])
df.head()

City  Population  Violent\ncrime  \
0             Adams Village      1851.0             0.0   
1  Addison Town and Village      2568.0             2.0   
2            Afton Village4       820.0             0.0   
3             Akron Village      2842.0             1.0   
4                   Albany4     98595.0           802.0   

   Murder and\nnonnegligent\nmanslaughter  Rape\n(revised\ndefinition)1  \
0                                     0.0                           NaN   
1                                     0.0                           NaN   
2                                     0.0                           0.0   
3                                     0.0                           NaN   
4                                     8.0                          54.0   

   Rape\n(legacy\ndefinition)2  Robbery  Aggravated\nassault  Property\ncrime  \
0                          0.0      0.0                  0.0             11.0   
1                          0.0      1.0                  1.0             49.0   
2                          NaN      0.0                  0.0              1.0   
3                          0.0      0.0                  1.0             17.0   
4                          NaN    237.0                503.0           3888.0   

   Burglary  Larceny-\ntheft  Motor\nvehicle\ntheft  Arson3  
0       1.0             10.0                    0.0     0.0  
1       1.0             47.0                    1.0     0.0  
2       0.0              1.0                    0.0     0.0  
3       0.0             17.0                    0.0     0.0  
4     683.0           3083.0                  122.0    12.0

In [26]:
df.columns

Index(['City', 'Population', 'Violent\ncrime',
       'Murder and\nnonnegligent\nmanslaughter',
       'Rape\n(revised\ndefinition)1', 'Rape\n(legacy\ndefinition)2',
       'Robbery', 'Aggravated\nassault', 'Property\ncrime', 'Burglary',
       'Larceny-\ntheft', 'Motor\nvehicle\ntheft', 'Arson3', 'Murder_stand',
       'Robbery_stand'],
      dtype='object')

In [25]:
# converted features into values per 1000 people to standardization purpose

test=pd.DataFrame()
test['Population']=df['Population']
# test['Murder_stand']=df['Murder and\nnonnegligent\nmanslaughter']/df['Population']*1000
test['Robbery_stand']=df['Robbery']/df['Population']*1000
# test['Assault_stand']=df['Aggravated\nassault']/df['Population']*1000
test['Burglary_stand']=df['Burglary']/df['Population']*1000
test['Larceny_stand']=df['Larceny-\ntheft']/df['Population']*1000
# test['Vehicle_stand']=df['Motor\nvehicle\ntheft']/df['Population']*1000
# test['Arson_stand']=df['Arson3']/df['Population']*1000
test['Propertycrime']=df['Property\ncrime']/df['Population']*1000

test.head()
test=test.dropna()

In [26]:
display(test.corr())

Population  Robbery_stand  Burglary_stand  Larceny_stand  \
Population        1.000000       0.165978       -0.000809       0.004246   
Robbery_stand     0.165978       1.000000        0.455290       0.215906   
Burglary_stand   -0.000809       0.455290        1.000000       0.801190   
Larceny_stand     0.004246       0.215906        0.801190       1.000000   
Propertycrime     0.005580       0.274566        0.856969       0.994579   

                Propertycrime  
Population           0.005580  
Robbery_stand        0.274566  
Burglary_stand       0.856969  
Larceny_stand        0.994579  
Propertycrime        1.000000

There are some high correlation between Robbery and Burglary, Larceny and Burglary. These pairs should not be included in the model together. <br>
First, we decided to test out model which is <br>
**'The number of Property crime for 1000 people = Robbery, Burglary and Larcenry each'**<br>
The three features seem to be highly correlated with property crime, thus decided to be tested first. 

In [30]:
# Test your model with different holdout groups.
data=test[['Robbery_stand']]#,'Burglary_stand','Robbery_stand','Murder_stand']]
target=test['Propertycrime']

# Use train_test_split to create the necessary training and test groups
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=20)
print('With 20% Holdout: ' + str(regr.fit(X_train, y_train).score(X_test, y_test)))
print('Testing on Sample: ' + str(regr.fit(data, target).score(data, target)))

# cross validation
cross_val_score(regr,data,target, cv=10)

With 20% Holdout: 0.10811481682979307
Testing on Sample: 0.07538641941479018


array([ 0.27725568,  0.33199506,  0.09894963, -0.22488251,  0.12292125,
        0.21635098, -0.04338042,  0.14386462,  0.33038169,  0.07888631])

The score is not consistent among the folds.

In [29]:
# Test your model with different holdout groups.
data=test[['Burglary_stand']]#,'Burglary_stand','Robbery_stand','Murder_stand']]
target=test['Propertycrime']

# Use train_test_split to create the necessary training and test groups
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=20)
print('With 20% Holdout: ' + str(regr.fit(X_train, y_train).score(X_test, y_test)))
print('Testing on Sample: ' + str(regr.fit(data, target).score(data, target)))

# cross validation
cross_val_score(regr,data,target, cv=10)

With 20% Holdout: 0.28971464700882155
Testing on Sample: 0.7343963190989359


array([ 0.61545702,  0.58170796,  0.63767806,  0.27789086,  0.48148197,
       -0.04078094,  0.72118109,  0.45835528,  0.51555775,  0.57548751])

The score is not consistent among the folds.

In [64]:
# Test your model with different holdout groups.
data=test[['Larceny_stand']]#,'Burglary_stand','Robbery_stand','Murder_stand']]
target=test['Propertycrime']

# Use train_test_split to create the necessary training and test groups
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=20)
print('With 20% Holdout: ' + str(regr.fit(X_train, y_train).score(X_test, y_test)))
print('Testing on Sample: ' + str(regr.fit(data, target).score(data, target)))

# cross validation
cross_val_score(regr,data,target, cv=10)

With 20% Holdout: 0.9739984777032402
Testing on Sample: 0.9897853095036151


array([0.98233403, 0.98068189, 0.98568999, 0.97682881, 0.98299224,
       0.94795422, 0.99746342, 0.95959183, 0.95978453, 0.98086479])

The score is high and consistent when using both holdout and cross validation.

In [77]:
import statsmodels.formula.api as smf
from statsmodels.sandbox.regression.predstd import wls_prediction_std

lm=smf.ols(formula='Propertycrime ~ Larceny_stand', data=test).fit()
print('estimates\n',lm.params)
print('pvalues\n',lm.pvalues)
print('R-squared\n',lm.rsquared)

estimates
 Intercept        0.994523
Larceny_stand    1.150783
dtype: float64
pvalues
 Intercept        2.065593e-12
Larceny_stand    0.000000e+00
dtype: float64
R-squared
 0.989785309503615


When examining parameter estimates and p values for each, Larceny is highly significant.<br>
We can conclude the number of larceny per 1000 people only can predict the number of property crime per 1000 people. 