In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

We're ready to build our first neural network. We will have multiple features we feed into our model, each of which will go through a set of perceptron models to arrive at a response which will be trained to our output.

Like many models we've covered, this can be used as both a regression or classification model.

First, we need to load our dataset. For this example we'll use The Museum of Modern Art in New York's [public dataset](https://media.githubusercontent.com/media/MuseumofModernArt/collection/master/Artworks.csv) on their collection.

In [2]:
artworks = pd.read_csv('https://media.githubusercontent.com/media/MuseumofModernArt/collection/master/Artworks.csv')

In [3]:
artworks.columns

Index(['Title', 'Artist', 'ConstituentID', 'ArtistBio', 'Nationality',
       'BeginDate', 'EndDate', 'Gender', 'Date', 'Medium', 'Dimensions',
       'CreditLine', 'AccessionNumber', 'Classification', 'Department',
       'DateAcquired', 'Cataloged', 'ObjectID', 'URL', 'ThumbnailURL',
       'Circumference (cm)', 'Depth (cm)', 'Diameter (cm)', 'Height (cm)',
       'Length (cm)', 'Weight (kg)', 'Width (cm)', 'Seat Height (cm)',
       'Duration (sec.)'],
      dtype='object')

In [4]:
artworks.head()

Title  \
0  Ferdinandsbrücke Project, Vienna, Austria, Ele...   
1  City of Music, National Superior Conservatory ...   
2  Villa near Vienna Project, Outside Vienna, Aus...   
3  The Manhattan Transcripts Project, New York, N...   
4  Villa, project, outside Vienna, Austria, Exter...   

                     Artist ConstituentID  \
0               Otto Wagner          6210   
1  Christian de Portzamparc          7470   
2                Emil Hoppe          7605   
3           Bernard Tschumi          7056   
4                Emil Hoppe          7605   

                                   ArtistBio Nationality BeginDate EndDate  \
0                      (Austrian, 1841–1918)  (Austrian)    (1841)  (1918)   
1                        (French, born 1944)    (French)    (1944)     (0)   
2                      (Austrian, 1876–1957)  (Austrian)    (1876)  (1957)   
3  (French and Swiss, born Switzerland 1944)          ()    (1944)     (0)   
4                      (Austrian, 1876–1957)  (Austrian)    (1876)  (1957)   

   Gender  Date                                             Medium  \
0  (Male)  1896      Ink and cut-and-pasted painted pages on paper   
1  (Male)  1987                  Paint and colored pencil on print   
2  (Male)  1903  Graphite, pen, color pencil, ink, and gouache ...   
3  (Male)  1980  Photographic reproduction with colored synthet...   
4  (Male)  1903  Graphite, color pencil, ink, and gouache on tr...   

        ...                                             ThumbnailURL  \
0       ...        http://www.moma.org/media/W1siZiIsIjU5NDA1Il0s...   
1       ...        http://www.moma.org/media/W1siZiIsIjk3Il0sWyJw...   
2       ...        http://www.moma.org/media/W1siZiIsIjk4Il0sWyJw...   
3       ...        http://www.moma.org/media/W1siZiIsIjEyNCJdLFsi...   
4       ...        http://www.moma.org/media/W1siZiIsIjEyNiJdLFsi...   

  Circumference (cm) Depth (cm) Diameter (cm) Height (cm) Length (cm)  \
0                NaN        NaN           NaN     48.6000         NaN   
1                NaN        NaN           NaN     40.6401         NaN   
2                NaN        NaN           NaN     34.3000         NaN   
3                NaN        NaN           NaN     50.8000         NaN   
4                NaN        NaN           NaN     38.4000         NaN   

  Weight (kg)  Width (cm) Seat Height (cm) Duration (sec.)  
0         NaN    168.9000              NaN             NaN  
1         NaN     29.8451              NaN             NaN  
2         NaN     31.8000              NaN             NaN  
3         NaN     50.8000              NaN             NaN  
4         NaN     19.1000              NaN             NaN  

[5 rows x 29 columns]

We'll also do a bit of data processing and cleaning, selecting columns of interest and converting URL's to booleans indicating whether they are present.

In [5]:
# Select Columns.
artworks = artworks[['Artist', 'Nationality', 'Gender', 'Date', 'Department',
                    'DateAcquired', 'URL', 'ThumbnailURL', 'Height (cm)', 'Width (cm)']]

# Convert URL's to booleans.
artworks['URL'] = artworks['URL'].notnull()
artworks['ThumbnailURL'] = artworks['ThumbnailURL'].notnull()

# Drop films and some other tricky rows.
artworks = artworks[artworks['Department']!='Film']
artworks = artworks[artworks['Department']!='Media and Performance Art']
artworks = artworks[artworks['Department']!='Fluxus Collection']

# Drop missing data.
artworks = artworks.dropna()

In [6]:
artworks.head()

Artist Nationality  Gender  Date             Department  \
0               Otto Wagner  (Austrian)  (Male)  1896  Architecture & Design   
1  Christian de Portzamparc    (French)  (Male)  1987  Architecture & Design   
2                Emil Hoppe  (Austrian)  (Male)  1903  Architecture & Design   
3           Bernard Tschumi          ()  (Male)  1980  Architecture & Design   
4                Emil Hoppe  (Austrian)  (Male)  1903  Architecture & Design   

  DateAcquired   URL  ThumbnailURL  Height (cm)  Width (cm)  
0   1996-04-09  True          True      48.6000    168.9000  
1   1995-01-17  True          True      40.6401     29.8451  
2   1997-01-15  True          True      34.3000     31.8000  
3   1995-01-17  True          True      50.8000     50.8000  
4   1997-01-15  True          True      38.4000     19.1000

In [7]:
artworks['Department'].unique()

array(['Architecture & Design', 'Drawings & Prints',
       'Painting & Sculpture', 'Photography', 'Media and Performance'],
      dtype=object)

## Building a Model

Now, let's see if we can use multi-layer perceptron modeling (or "MLP") to see if we can classify the department a piece should go into using everything but the department name.

Before we import MLP from SKLearn and establish the model we first have to ensure correct typing for our data and do some other cleaning.

In [8]:
# Get data types.
artworks.dtypes

Artist           object
Nationality      object
Gender           object
Date             object
Department       object
DateAcquired     object
URL                bool
ThumbnailURL       bool
Height (cm)     float64
Width (cm)      float64
dtype: object

The `DateAcquired` column is an object. Let's transform that to a datetime object and add a feature for just the year the artwork was acquired.

In [9]:
artworks['DateAcquired'] = pd.to_datetime(artworks.DateAcquired)
artworks['YearAcquired'] = artworks.DateAcquired.dt.year
artworks['YearAcquired'].dtype

dtype('int64')

Great. Let's do some more miscellaneous cleaning.

In [14]:
# Remove multiple nationalities, genders, and artists.
artworks.loc[artworks['Gender'].str.contains('\) \('), 'Gender'] = '\(multiple_persons\)'
artworks.loc[artworks['Nationality'].str.contains('\) \('), 'Nationality'] = '\(multiple_nationalities\)'
artworks.loc[artworks['Artist'].str.contains(','), 'Artist'] = 'Multiple_Artists'

# Convert dates to start date, cutting down number of distinct examples.
artworks['Date'] = pd.Series(artworks.Date.str.extract(
    '([0-9]{4})', expand=False))[:-1]

# Final column drops and NA drop.
X = artworks.drop(['Department', 'DateAcquired', 'Artist', 'Nationality', 'Date'], 1)

# Create dummies separately.
artists = pd.get_dummies(artworks.Artist)
nationalities = pd.get_dummies(artworks.Nationality)
dates = pd.get_dummies(artworks.Date)

# Concat with other variables, but artists slows this wayyyyy down so we'll keep it out for now
X = pd.get_dummies(X) #, sparse=True
X = pd.concat([X, nationalities, dates], axis=1)

Y = artworks.Department

In [16]:
X.head()

URL  ThumbnailURL  Height (cm)  Width (cm)  YearAcquired  Gender_()  \
0  True          True      48.6000    168.9000          1996          0   
1  True          True      40.6401     29.8451          1995          0   
2  True          True      34.3000     31.8000          1997          0   
3  True          True      50.8000     50.8000          1995          0   
4  True          True      38.4000     19.1000          1997          0   

   Gender_(Female)  Gender_(Male)  Gender_(male)  Gender_\(multiple_persons\)  \
0                0              1              0                            0   
1                0              1              0                            0   
2                0              1              0                            0   
3                0              1              0                            0   
4                0              1              0                            0   

   ...   2009  2010  2011  2012  2013  2014  2015  2016  2017  2018  
0  ...      0     0     0     0     0     0     0     0     0     0  
1  ...      0     0     0     0     0     0     0     0     0     0  
2  ...      0     0     0     0     0     0     0     0     0     0  
3  ...      0     0     0     0     0     0     0     0     0     0  
4  ...      0     0     0     0     0     0     0     0     0     0  

[5 rows x 318 columns]

In [29]:
# Alright! We've done our prep, let's build the model.
# Neural networks are hugely computationally intensive.
# This may take several minutes to run.

# Import the model.
from sklearn.neural_network import MLPClassifier

# Establish and fit the model, with a single, 1000 perceptron layer.
mlp = MLPClassifier(hidden_layer_sizes=(1000,))
mlp.fit(X, Y)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(1000,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [30]:
mlp.score(X, Y)

0.7029446581828943

In [31]:
Y.value_counts()/len(Y)

Drawings & Prints        0.623002
Photography              0.226630
Architecture & Design    0.113171
Painting & Sculpture     0.033590
Media and Performance    0.003607
Name: Department, dtype: float64

In [32]:
from sklearn.model_selection import cross_val_score
cross_val_score(mlp, X, Y, cv=5)

array([0.69727655, 0.71382993, 0.62275145, 0.47121387, 0.57510174])

Now we got a lot of information from all of this. Firstly we can see that the model seems to overfit, though there is still so remaining performance when validated with cross validation. This is a feature of neural networks that aren't given enough data for the number of features present. _Neural networks, in general, like_ a lot _of data_. You may also have noticed something also about neural networks: _they can take a_ long _time to run_. Try increasing the layer size by adding a zero. Feel free to interrupt the kernel if you don't have time...

Also note that we created bools for artist's name but left them out. Both of the above points are the reason for that. It would take much longer to run and it would be much more prone to overfitting.

## Model parameters

Now, before we move on and let you loose with some tasks to work on the model, let's go over the parameters.

We included one parameter: hidden layer size. Remember in the previous lesson, when we talked about layers in a neural network. This tells us how many and how big to make our layers. Pass in a tuple that specifies each layer's size. Our network is 1000 neurons wide and one layer. (100, 4, ) would create a network with two layers, one 100 wide and the other 4.

How many layers to include is determined by two things: computational resources and cross validation searching for convergence. It's generally less than the number of input variables you have.

You can also set an alpha. Neural networks like this use a regularization parameter that penalizes large coefficients just like we discussed in the advanced regression section. Alpha scales that penalty.

Lastly, we'll discuss the activation function. The activation function determines whether the output from an individual perceptron is binary or continuous. By default this is a 'relu', or 'rectified linear unit function' function. In the exercise we went through earlier we used this binary function, but we discussed the _sigmoid_ as a reasonable alternative. The _sigmoid_ (called 'logistic' by SKLearn because it's a 'logistic sigmoid function') allows for continuous variables between 0 and 1, which allows for a more nuanced model. It does come at the cost of increased computational complexity.

If you want to learn more about these, study [activation functions](https://en.wikipedia.org/wiki/Activation_function) and [multilayer perceptrons](https://en.wikipedia.org/wiki/Multilayer_perceptron). The [Deep Learning](http://www.deeplearningbook.org/) book referenced earlier goes into great detail on the linear algebra involved.

You could also just test the models with cross validation. Unless neural networks are your specialty cross validation should be sufficient.

For the other parameters and their defaults, check out the [MLPClassifier documentaiton](http://scikit-learn.org/stable/modules/generated/sklearn.neural_network.MLPClassifier.html#sklearn.neural_network.MLPClassifier).

## Drill: Playing with layers

Now it's your turn. Using the space below, experiment with different hidden layer structures. You can try this on a subset of the data to improve runtime. See how things vary. See what seems to matter the most. Feel free to manipulate other parameters as well. It may also be beneficial to do some real feature selection work...

## 100 hidden layers

In [20]:
# Import the model.
from sklearn.neural_network import MLPClassifier

# Establish and fit the model, with a single, 100 perceptron layer.(default)
mlp = MLPClassifier(random_state=1)
mlp.fit(X, Y,)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='adam', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

In [21]:
mlp.score(X, Y)

0.7090022935779816

In [22]:
from sklearn.model_selection import cross_val_score
ans=cross_val_score(mlp, X, Y, cv=5,n_jobs = -1)
ans

array([0.67087437, 0.71660424, 0.66076301, 0.55042775, 0.64645764])

In [23]:
print(ans.mean(),ans.std())

0.6490254011598637 0.05460794807225514


## Logistic sigmoid function

In [24]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score
mlp2 = MLPClassifier(activation='logistic',random_state=1)
ans2=cross_val_score(mlp2, X, Y, cv=5)
ans2

array([0.68368243, 0.73852129, 0.64166474, 0.66187283, 0.57843137])

In [25]:
print(ans2.mean(),ans2.std())

0.6608345343252615 0.05237575606801331


sigmoid function showed sligtly better performance than relu.

## Alpha

In [26]:
# default 0.0001
mlp3 = MLPClassifier(alpha=1e-5,random_state=1)
ans3 = cross_val_score(mlp3, X, Y, cv=5)
print(ans3)
print(ans3.mean(),ans3.std())

[0.35908818 0.6785962  0.64957225 0.52647399 0.59642064]
0.5620302525030447 0.11391545550986942


In [27]:
mlp4 = MLPClassifier(alpha=1e-6,random_state=1)
ans4 = cross_val_score(mlp4, X, Y, cv=5)
print(ans4)
print(ans4.mean(),ans4.std())

[0.49895963 0.71660424 0.65253179 0.66145665 0.63161302]
0.6322330680718204 0.07231423644633239


In [33]:
mlp6 = MLPClassifier(alpha=1e-7,random_state=1)
ans6 = cross_val_score(mlp6, X, Y, cv=5)
print(ans6)
print(ans6.mean(),ans6.std())

[0.44712628 0.70805012 0.66099422 0.6176185  0.56386422]
0.5995306683137591 0.0898672389800048


1e-6 alpha performed the best, but its performance was still lower than that of sigmoid function.

## More layers

In [34]:
mlp5 = MLPClassifier(hidden_layer_sizes=(100,100), random_state=1)
ans5 = cross_val_score(mlp5, X, Y, cv=5, n_jobs=-1)
print(ans5)
print(ans5.mean(),ans5.std())

[0.66000832 0.71272021 0.68841618 0.60776879 0.55646504]
0.6450757087442431 0.056428389673649576


In [35]:
mlp7 = MLPClassifier(hidden_layer_sizes=(100,100,100), random_state=1)
ans7 = cross_val_score(mlp7, X, Y, cv=5,n_jobs=-1)
print(ans7)
print(ans7.mean(),ans7.std())

[0.72751653 0.72894992 0.68823121 0.66811561 0.58152978]
0.6788686113005667 0.05394977487404173


In [38]:
mlp9 = MLPClassifier(hidden_layer_sizes=(100,100,100,100), random_state=1)
ans9 = cross_val_score(mlp9, X, Y, cv=5,n_jobs=-1)
print(ans9)
print(ans9.mean(),ans9.std())

[0.70772645 0.74291395 0.6713526  0.69313295 0.61320755]
0.6856666999004927 0.04306935678212543


## Combination of best parameters

In [39]:
mlp8 = MLPClassifier(hidden_layer_sizes=(100,100,100,100),alpha=1e-6,activation='logistic', random_state=1)
ans8 = cross_val_score(mlp8, X, Y, cv=5,n_jobs=-1)
print(ans8)
print(ans8.mean(),ans8.std())

[0.68654922 0.72945855 0.66011561 0.64319075 0.61764706]
0.6673922370545451 0.038294806153151346


- The performance for the combination of best params couldn't exceed the performance of 4 layer itself.
- Addition of the number of layer seems the most important factor to improve accuracy of neural net.